apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpdump-deployment
  labels:
    app: httpdump
spec:
  selector:
    matchLabels:
      app: httpdump
  template:
    metadata:
      labels:
        app: httpdump
    spec:
      containers:
        - name: httpdump
          image: liamylian/httpdump-arm64
          ports:
            - containerPort: 80
              hostPort: 8010
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64

---

apiVersion: v1
kind: Service
metadata:
  name: httpdump-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: httpdump
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80